server.port=8080

# Base A - dados principais do domínio
app.datasource.main.url=jdbc:h2:file:./data/principal_db;AUTO_SERVER=TRUE
app.datasource.main.username=sa
app.datasource.main.password=
app.datasource.main.driver-class-name=org.h2.Driver

# Base B - auditoria/log
app.datasource.audit.url=jdbc:h2:file:./data/audit_db;AUTO_SERVER=TRUE
app.datasource.audit.username=sa
app.datasource.audit.password=
app.datasource.audit.driver-class-name=org.h2.Driver

spring.jpa.show-sql=true
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
